application: glassbabylog
version: 1
runtime: php
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: public/img/favicon.ico
  upload: public/img/favicon\.ico
- url: /logo\.png.*
  static_files: public/img/logo.png
  upload: public/img/logo\.png
- url: /api.*
  script: public/index.php
- url: /components
  static_dir: public/app/components
- url: /images
  static_dir: public/app/images
- url: /scripts
  static_dir: public/app/scripts
- url: /styles
  static_dir: public/app/styles
- url: /views
  static_dir: public/app/views
- url: /.*
  script: public/app/index.html