application: glassbabylog
version: 1
runtime: php
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: public/img/favicon.ico
  upload: public/img/favicon\.ico
- url: /logo\.png.*
  static_files: public/img/logo.png
  upload: public/img/logo\.png
- url: /app/components
  static_dir: public/app/components
- url: /app/images
  static_dir: public/app/images
- url: /app/scripts
  static_dir: public/app/scripts
- url: /app/styles
  static_dir: public/app/styles
- url: /app/views
  static_dir: public/app/views
- url: /app/.*
  script: public/app/index.html
- url: /css
  static_dir: public/css
- url: /img
  static_dir: public/img
- url: /js
  static_dir: public/js
- url: /phpinfo
  script: phpinfo.php
- url: /.*
  script: public/index.php