CREATE TABLE babies (
  id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER DEFAULT NULL,
  name TEXT(150) DEFAULT NULL,
  dob TEXT DEFAULT NULL,
  interval INTEGER DEFAULT NULL,
  remind_interval INTEGER DEFAULT NULL
);
CREATE TABLE user (
  id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT(150) DEFAULT NULL,
  email TEXT(150) DEFAULT NULL,
  refresh_token TEXT(150) DEFAULT NULL,
  date_added TEXT DEFAULT NULL
);
CREATE TABLE log (
  id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
  baby_id INTEGER DEFAULT NULL,
  action TEXT(150) DEFAULT NULL,
  timestamp TEXT DEFAULT NULL
);